grab_html_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('webpageplaylist/', include('webpage_playlist.urls', namespace="webpageplaylist"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup')
]

webpage_playlist/urls.py
from django.urls import path


from .views import UrlSubmission, UseWebpage

app_name = "webpageplaylist"

urlpatterns = [

    path('url_submission/', UrlSubmission.as_view(), name='url_sub' ),
    path('user_webpage/', UseWebpage.as_view(), name='use_webpage')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    # user_name = models.CharField(max_length=255)
    # email = models.EmailField()
    pass


    def __str__(self):
        return self.email

webpage_playlist/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class UserUrl(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_url = models.TextField()
    submission_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user_url

class UserWebpage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_html = models.FileField(upload_to='media/')


    def __str__(self):
        return str(self.user)

class UserSongs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    artist = models.TextField()
    song = models.TextField()

    def __str__(self):
        return self.song

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = CustomUser
        fields = ('username', 'email')

webpage_playlist/forms.py
from django.forms import ModelForm
from .models import UserUrl

class UrlForm(ModelForm):
    class Meta:
        model=UserUrl
        fields = ['user_url']

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

# Create your views here.
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

webpage_playlist/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.core.files.base import ContentFile

from django.views import View
import requests as cf_request
import urllib.request

from .forms import UrlForm
from .models import UserUrl, UserWebpage

# Create your views here.
class UrlSubmission(View):
    form_class = UrlForm
    template_name = 'webpageplaylist/url_submission.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name,{'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            userurl = UserUrl()
            userurl.user_url = form.cleaned_data['user_url']
            userurl.user = request.user
            userurl.save()

            get_html = cf_request.get(form.cleaned_data['user_url'])
            get_html = get_html.text


            userwebpage = UserWebpage()
            userwebpage.user = request.user
            userwebpage.user_html.save('test4.html', ContentFile(get_html))
            h = userwebpage.user_html
            userwebpage.save()
            return render(request, template_name="webpageplaylist/user_webpage.html", context={'user_webpage':h})
            # return render(request, template_name="webpageplaylist/user_webpage.html")

class UseWebpage(View):

    def get(self, request, *args, **kwargs):
        user_recent_record = UserWebpage.objects.filter(user=request.user).order_by('-id')[0]
        user_html = user_recent_record.html
        return render(request=request, template_name=user_html)

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        Django Auth Tutorial
    {% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% block links %}

    {% endblock %}

    {#        <link rel="stylesheet" href="{% static "css/getSongData.css" %}">#}

</head>
<body>

    <main>
        {% block content %}
        
        {% endblock %}
    </main>

</body>

{% block scipts %}



{% endblock %}

</html>

templates/home.html
{% extends "base.html" %}


{% block title %}
    Home
{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        Hi {{ user.username }}
        <p><a href="{% url 'logout' %}">Logout</a></p>
        <p><a href="{% url 'webpageplaylist:url_sub' %}">Go to Url Submission</a></p>


    {% else %}

        <p>You are not logged in</p>
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'signup' %}">Signup</a>
    {% endif %}

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}

    Sign Up

{% endblock %}


{% block content %}

    <h2>Sign Up</h2>

    <form method="post">

        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">
            Sign Up
        </button>

    </form>


{% endblock %}

webpage_playlist/templates/webpageplaylist/url_submission.html
{% extends 'base.html' %}

{% block title %}

    Submit Url

{% endblock %}

{% block content %}

    <h1>Submit your url</h1>

    <form method="post">

        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">
            Submit Url
        </button>

    </form>

{% endblock %}

webpage_playlist/templates/webpageplaylist/user_webpage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}

    User Webpage

{% endblock %}

{% block links %}

        <link rel="stylesheet" href="{% static "css/getSongData.css" %}">
        <script src="{% static "js/getSongData.js" %}"></script>

{% endblock %}



{% block content %}

{#    <h1>User's Chosen Webpage</h1>#}
{#    <iframe src="{{ user_webpage.url }}" frameborder="0" width="800px"></iframe>#}

        <div class="container-fluid">

        <div class="row">
            <div class="col col-lg-8" align="left">
                <h4>Here is the iframe</h4>

                <iframe id="myIframe" src="{{ user_webpage.url }}" frameborder="1"></iframe>

                <h4 id="iframe_test">Get selected stuff here</h4>
                <div id="stuff"></div>


            </div>

            <div class="col col-lg-4">

                <h5>Click the letters that make up the artist name and song</h5>

                <button type="button" class="btn btn-secondary btn-sm" id="get_stuff">Get Iframe Stuff</button>

                <div class="container">
                    <div class="row">
                        <div class="col-sm-3 mx-auto">
                            <h6>Input</h6>
                        </div>
                        <div class="col-sm-9 border mx-auto">
                            <p id="full_name">#######</p>
                        </div>

                    </div>
                </div>




                <button type="button" class="btn btn-secondary btn-sm" id="get_select_artist" value="artist">Make Selectable</button>

                <h6>Selectable</h6>
                <div id="container_artist">
                    <h6 id="artist_name"></h6>
                </div>

                <button type="button" class="btn btn-secondary btn-sm" id="artist_button" value="artist">Get Selected</button>

                <h6>Selected Artist</h6>
                <p id="click_artist"></p>

                <h6>Remaining Text</h6>
                <p id="search_within_artist"></p>

                <h6>Input</h6>
                <h6 id="song_fullname"></h6>

                <button type="button" class="btn btn-secondary btn-sm" id="get_select_song" value="song">Make Selectable</button>

                <h6>Selectable</h6>
                <div id="container_song">
                    <h6 id="song_name"></h6>
                </div>

                <button type="button" class="btn btn-secondary btn-sm" id="song_button" value="song">Get Selected</button>

                <h6>Selected Song</h6>
                <h6 id="click_song"></h6>

                <h6>Remaining Text</h6>
                <h6 id="search_within_song"></h6>


                <!--<h6>Test Output</h6>-->

                <!--<h6>Input</h6>-->

                <!--<h6 id="test_fullname">"Come Fly With Me," by Frank Sinatra</h6>-->

                <button type="button" class="btn btn-secondary btn-sm" id="test_button">Test</button>

                <!--<h6>Output</h6>-->
                <!--<h6>Artist:</h6>-->
                <!--<p id="artist_output"></p>-->
                <!--<h6>Song:</h6>-->
                <!--<p id="song_output"></p>-->

            </div>
        </div>
        <div class="row">
            <div id="song_list" class="col col-lg-4">

                    <h6>Songs from Webpage</h6>

            </div>

            <div  class="col col-lg-4">



            </div>
            <div class="col col-lg-4"></div>

        </div>


    </div>

{% endblock %}

{% block scipts %}

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>


    <script src="https://thibaultjanbeyer.github.io/DragSelect/ds.min.js"></script>



{% endblock %}